// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: proto/storage/v1/storage.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_QueryShard_FullMethodName       = "/storage.v1.StorageService/QueryShard"
	StorageService_QueryShardStream_FullMethodName = "/storage.v1.StorageService/QueryShardStream"
	StorageService_GetShardInfo_FullMethodName     = "/storage.v1.StorageService/GetShardInfo"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService handles data storage and retrieval operations
type StorageServiceClient interface {
	// Query operations
	QueryShard(ctx context.Context, in *QueryShardRequest, opts ...grpc.CallOption) (*QueryShardResponse, error)
	// Streaming query - returns data in chunks for large datasets
	QueryShardStream(ctx context.Context, in *QueryShardStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryShardChunk], error)
	// Shard management
	GetShardInfo(ctx context.Context, in *GetShardInfoRequest, opts ...grpc.CallOption) (*GetShardInfoResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) QueryShard(ctx context.Context, in *QueryShardRequest, opts ...grpc.CallOption) (*QueryShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryShardResponse)
	err := c.cc.Invoke(ctx, StorageService_QueryShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) QueryShardStream(ctx context.Context, in *QueryShardStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryShardChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_QueryShardStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryShardStreamRequest, QueryShardChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_QueryShardStreamClient = grpc.ServerStreamingClient[QueryShardChunk]

func (c *storageServiceClient) GetShardInfo(ctx context.Context, in *GetShardInfoRequest, opts ...grpc.CallOption) (*GetShardInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_GetShardInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService handles data storage and retrieval operations
type StorageServiceServer interface {
	// Query operations
	QueryShard(context.Context, *QueryShardRequest) (*QueryShardResponse, error)
	// Streaming query - returns data in chunks for large datasets
	QueryShardStream(*QueryShardStreamRequest, grpc.ServerStreamingServer[QueryShardChunk]) error
	// Shard management
	GetShardInfo(context.Context, *GetShardInfoRequest) (*GetShardInfoResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) QueryShard(context.Context, *QueryShardRequest) (*QueryShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryShard not implemented")
}
func (UnimplementedStorageServiceServer) QueryShardStream(*QueryShardStreamRequest, grpc.ServerStreamingServer[QueryShardChunk]) error {
	return status.Error(codes.Unimplemented, "method QueryShardStream not implemented")
}
func (UnimplementedStorageServiceServer) GetShardInfo(context.Context, *GetShardInfoRequest) (*GetShardInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardInfo not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_QueryShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).QueryShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_QueryShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).QueryShard(ctx, req.(*QueryShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_QueryShardStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryShardStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).QueryShardStream(m, &grpc.GenericServerStream[QueryShardStreamRequest, QueryShardChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_QueryShardStreamServer = grpc.ServerStreamingServer[QueryShardChunk]

func _StorageService_GetShardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetShardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetShardInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetShardInfo(ctx, req.(*GetShardInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryShard",
			Handler:    _StorageService_QueryShard_Handler,
		},
		{
			MethodName: "GetShardInfo",
			Handler:    _StorageService_GetShardInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryShardStream",
			Handler:       _StorageService_QueryShardStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/storage/v1/storage.proto",
}
