// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/storage/v1/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldValue represents a single field value with support for multiple types
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_NumberValue
	//	*FieldValue_StringValue
	//	*FieldValue_BoolValue
	//	*FieldValue_IntValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"` // For numeric values (including floats)
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"` // For string values
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"` // For boolean values
}

type FieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"` // For integer values
}

func (*FieldValue_NumberValue) isFieldValue_Value() {}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

func (*FieldValue_IntValue) isFieldValue_Value() {}

// FieldsEntry represents fields for a single data point in storage
type FieldsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*FieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsEntry) Reset() {
	*x = FieldsEntry{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsEntry) ProtoMessage() {}

func (x *FieldsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsEntry.ProtoReflect.Descriptor instead.
func (*FieldsEntry) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FieldsEntry) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// DeviceBlock represents a compressed block of data for a single device
// Uses delta encoding for timestamps and protobuf for field data
type DeviceBlock struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntryCount uint32                 `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// Delta-encoded timestamps
	BaseTime int64    `protobuf:"varint,3,opt,name=base_time,json=baseTime,proto3" json:"base_time,omitempty"` // First timestamp (Unix nano)
	Deltas   []uint32 `protobuf:"varint,4,rep,packed,name=deltas,proto3" json:"deltas,omitempty"`              // Delta from previous timestamp (milliseconds)
	// Field data for each point (protobuf instead of JSON)
	Fields        []*FieldsEntry `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceBlock) Reset() {
	*x = DeviceBlock{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBlock) ProtoMessage() {}

func (x *DeviceBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBlock.ProtoReflect.Descriptor instead.
func (*DeviceBlock) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceBlock) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceBlock) GetEntryCount() uint32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *DeviceBlock) GetBaseTime() int64 {
	if x != nil {
		return x.BaseTime
	}
	return 0
}

func (x *DeviceBlock) GetDeltas() []uint32 {
	if x != nil {
		return x.Deltas
	}
	return nil
}

func (x *DeviceBlock) GetFields() []*FieldsEntry {
	if x != nil {
		return x.Fields
	}
	return nil
}

// AggregatedFieldValue represents statistics for an aggregated field
type AggregatedFieldValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`                              // Number of raw points
	Sum           float64                `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`                                 // Sum of values
	Avg           float64                `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`                                 // Average
	Min           float64                `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`                                 // Minimum
	Max           float64                `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`                                 // Maximum
	SumSquares    float64                `protobuf:"fixed64,6,opt,name=sum_squares,json=sumSquares,proto3" json:"sum_squares,omitempty"` // For variance calculation (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedFieldValue) Reset() {
	*x = AggregatedFieldValue{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedFieldValue) ProtoMessage() {}

func (x *AggregatedFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedFieldValue.ProtoReflect.Descriptor instead.
func (*AggregatedFieldValue) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *AggregatedFieldValue) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregatedFieldValue) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *AggregatedFieldValue) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *AggregatedFieldValue) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AggregatedFieldValue) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AggregatedFieldValue) GetSumSquares() float64 {
	if x != nil {
		return x.SumSquares
	}
	return 0
}

// AggregatedFieldsEntry represents aggregated fields for one time bucket
type AggregatedFieldsEntry struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Fields        map[string]*AggregatedFieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Complete      bool                             `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"` // Is this bucket complete?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedFieldsEntry) Reset() {
	*x = AggregatedFieldsEntry{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedFieldsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedFieldsEntry) ProtoMessage() {}

func (x *AggregatedFieldsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedFieldsEntry.ProtoReflect.Descriptor instead.
func (*AggregatedFieldsEntry) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedFieldsEntry) GetFields() map[string]*AggregatedFieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AggregatedFieldsEntry) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

// AggregatedDeviceBlock represents aggregated data for a single device
type AggregatedDeviceBlock struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EntryCount uint32                 `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// Timestamps for each aggregate point (no delta encoding needed, fewer points)
	Timestamps []int64 `protobuf:"varint,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"` // UnixNano for each aggregate point
	// Aggregated field data
	Fields []*AggregatedFieldsEntry `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	// Metadata
	AggregationLevel string `protobuf:"bytes,5,opt,name=aggregation_level,json=aggregationLevel,proto3" json:"aggregation_level,omitempty"` // "1h", "1d", "1M", "1y"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregatedDeviceBlock) Reset() {
	*x = AggregatedDeviceBlock{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedDeviceBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedDeviceBlock) ProtoMessage() {}

func (x *AggregatedDeviceBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedDeviceBlock.ProtoReflect.Descriptor instead.
func (*AggregatedDeviceBlock) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *AggregatedDeviceBlock) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AggregatedDeviceBlock) GetEntryCount() uint32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *AggregatedDeviceBlock) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *AggregatedDeviceBlock) GetFields() []*AggregatedFieldsEntry {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AggregatedDeviceBlock) GetAggregationLevel() string {
	if x != nil {
		return x.AggregationLevel
	}
	return ""
}

// QueryShardRequest queries data from a specific shard
type QueryShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`                               // Device IDs to query (empty = all)
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp in milliseconds
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp in milliseconds
	Fields        []string               `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`                         // Fields to return (empty = all)
	Limit         uint32                 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                          // Max results per device
	Interval      string                 `protobuf:"bytes,9,opt,name=interval,proto3" json:"interval,omitempty"`                     // Interval: 1m, 5m, 1h, 1d, 1mo, 1y (empty = raw)
	Aggregation   string                 `protobuf:"bytes,10,opt,name=aggregation,proto3" json:"aggregation,omitempty"`              // Aggregation: sum, avg, min, max (default: sum)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryShardRequest) Reset() {
	*x = QueryShardRequest{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryShardRequest) ProtoMessage() {}

func (x *QueryShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryShardRequest.ProtoReflect.Descriptor instead.
func (*QueryShardRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *QueryShardRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *QueryShardRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryShardRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryShardRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QueryShardRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryShardRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryShardRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryShardRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryShardRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *QueryShardRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

// QueryShardResponse returns query results
type QueryShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShardId       uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Results       []*DataPointResult     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryShardResponse) Reset() {
	*x = QueryShardResponse{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryShardResponse) ProtoMessage() {}

func (x *QueryShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryShardResponse.ProtoReflect.Descriptor instead.
func (*QueryShardResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *QueryShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryShardResponse) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *QueryShardResponse) GetResults() []*DataPointResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryShardResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryShardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DataPointResult groups data points by device ID
type DataPointResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataPoints    []*DataPoint           `protobuf:"bytes,2,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointResult) Reset() {
	*x = DataPointResult{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointResult) ProtoMessage() {}

func (x *DataPointResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointResult.ProtoReflect.Descriptor instead.
func (*DataPointResult) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *DataPointResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataPointResult) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

// DataPoint represents a single time-series data point
type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`                                                                              // Unix timestamp in milliseconds
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Device ID
	Fields        map[string]*FieldValue `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Field values (multi-type support)
	InsertedAt    int64                  `protobuf:"varint,4,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`                                                // System timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *DataPoint) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *DataPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataPoint) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataPoint) GetInsertedAt() int64 {
	if x != nil {
		return x.InsertedAt
	}
	return 0
}

// GetShardInfoRequest requests shard metadata
type GetShardInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardInfoRequest) Reset() {
	*x = GetShardInfoRequest{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardInfoRequest) ProtoMessage() {}

func (x *GetShardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardInfoRequest.ProtoReflect.Descriptor instead.
func (*GetShardInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *GetShardInfoRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

// GetShardInfoResponse returns shard metadata
type GetShardInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShardId          uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Database         string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Collection       string                 `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	StartTime        int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DataPointCount   uint64                 `protobuf:"varint,7,opt,name=data_point_count,json=dataPointCount,proto3" json:"data_point_count,omitempty"`
	MemoryUsageBytes uint64                 `protobuf:"varint,8,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	DiskUsageBytes   uint64                 `protobuf:"varint,9,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetShardInfoResponse) Reset() {
	*x = GetShardInfoResponse{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardInfoResponse) ProtoMessage() {}

func (x *GetShardInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardInfoResponse.ProtoReflect.Descriptor instead.
func (*GetShardInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *GetShardInfoResponse) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *GetShardInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetShardInfoResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetShardInfoResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetShardInfoResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetShardInfoResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetShardInfoResponse) GetDataPointCount() uint64 {
	if x != nil {
		return x.DataPointCount
	}
	return 0
}

func (x *GetShardInfoResponse) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *GetShardInfoResponse) GetDiskUsageBytes() uint64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

func (x *GetShardInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// QueryShardStreamRequest for streaming queries
type QueryShardStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []string               `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`                                // Device IDs to query (empty = all)
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`  // Unix timestamp in milliseconds
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`        // Unix timestamp in milliseconds
	Fields        []string               `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`                          // Fields to return (empty = all)
	Interval      string                 `protobuf:"bytes,8,opt,name=interval,proto3" json:"interval,omitempty"`                      // Interval: 1m, 5m, 1h, 1d, 1mo, 1y (empty = raw)
	Aggregation   string                 `protobuf:"bytes,9,opt,name=aggregation,proto3" json:"aggregation,omitempty"`                // Aggregation: sum, avg, min, max (default: sum)
	ChunkSize     uint32                 `protobuf:"varint,10,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // Number of data points per chunk (default: 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryShardStreamRequest) Reset() {
	*x = QueryShardStreamRequest{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryShardStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryShardStreamRequest) ProtoMessage() {}

func (x *QueryShardStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryShardStreamRequest.ProtoReflect.Descriptor instead.
func (*QueryShardStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *QueryShardStreamRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *QueryShardStreamRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryShardStreamRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryShardStreamRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QueryShardStreamRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryShardStreamRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryShardStreamRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryShardStreamRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *QueryShardStreamRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *QueryShardStreamRequest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// QueryShardChunk represents a chunk of streaming results
type QueryShardChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       uint32                 `protobuf:"varint,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // Chunk sequence number (0-based)
	ShardId       uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"` // Shard this chunk came from
	Results       []*DataPointResult     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`                 // Data points in this chunk
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                    // Number of data points in this chunk
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // True if this is the last chunk
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                     // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryShardChunk) Reset() {
	*x = QueryShardChunk{}
	mi := &file_proto_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryShardChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryShardChunk) ProtoMessage() {}

func (x *QueryShardChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryShardChunk.ProtoReflect.Descriptor instead.
func (*QueryShardChunk) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *QueryShardChunk) GetChunkId() uint32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *QueryShardChunk) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *QueryShardChunk) GetResults() []*DataPointResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryShardChunk) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryShardChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *QueryShardChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_storage_v1_storage_proto protoreflect.FileDescriptor

const file_proto_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/storage/v1/storage.proto\x12\n" +
	"storage.v1\"\x9f\x01\n" +
	"\n" +
	"FieldValue\x12#\n" +
	"\fnumber_value\x18\x01 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x03H\x00R\bintValueB\a\n" +
	"\x05value\"\x9d\x01\n" +
	"\vFieldsEntry\x12;\n" +
	"\x06fields\x18\x01 \x03(\v2#.storage.v1.FieldsEntry.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.storage.v1.FieldValueR\x05value:\x028\x01\"\xb1\x01\n" +
	"\vDeviceBlock\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\rR\n" +
	"entryCount\x12\x1b\n" +
	"\tbase_time\x18\x03 \x01(\x03R\bbaseTime\x12\x16\n" +
	"\x06deltas\x18\x04 \x03(\rR\x06deltas\x12/\n" +
	"\x06fields\x18\x05 \x03(\v2\x17.storage.v1.FieldsEntryR\x06fields\"\x95\x01\n" +
	"\x14AggregatedFieldValue\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03avg\x18\x03 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x01R\x03max\x12\x1f\n" +
	"\vsum_squares\x18\x06 \x01(\x01R\n" +
	"sumSquares\"\xd7\x01\n" +
	"\x15AggregatedFieldsEntry\x12E\n" +
	"\x06fields\x18\x01 \x03(\v2-.storage.v1.AggregatedFieldsEntry.FieldsEntryR\x06fields\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x1a[\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .storage.v1.AggregatedFieldValueR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x15AggregatedDeviceBlock\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\rR\n" +
	"entryCount\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x03 \x03(\x03R\n" +
	"timestamps\x129\n" +
	"\x06fields\x18\x04 \x03(\v2!.storage.v1.AggregatedFieldsEntryR\x06fields\x12+\n" +
	"\x11aggregation_level\x18\x05 \x01(\tR\x10aggregationLevel\"\xa2\x02\n" +
	"\x11QueryShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12\x14\n" +
	"\x05limit\x18\b \x01(\rR\x05limit\x12\x1a\n" +
	"\binterval\x18\t \x01(\tR\binterval\x12 \n" +
	"\vaggregation\x18\n" +
	" \x01(\tR\vaggregation\"\xac\x01\n" +
	"\x12QueryShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId\x125\n" +
	"\aresults\x18\x03 \x03(\v2\x1b.storage.v1.DataPointResultR\aresults\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"Y\n" +
	"\x0fDataPointResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\vdata_points\x18\x02 \x03(\v2\x15.storage.v1.DataPointR\n" +
	"dataPoints\"\xde\x01\n" +
	"\tDataPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x129\n" +
	"\x06fields\x18\x03 \x03(\v2!.storage.v1.DataPoint.FieldsEntryR\x06fields\x12\x1f\n" +
	"\vinserted_at\x18\x04 \x01(\x03R\n" +
	"insertedAt\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.storage.v1.FieldValueR\x05value:\x028\x01\"0\n" +
	"\x13GetShardInfoRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\"\xda\x02\n" +
	"\x14GetShardInfoResponse\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12(\n" +
	"\x10data_point_count\x18\a \x01(\x04R\x0edataPointCount\x12,\n" +
	"\x12memory_usage_bytes\x18\b \x01(\x04R\x10memoryUsageBytes\x12(\n" +
	"\x10disk_usage_bytes\x18\t \x01(\x04R\x0ediskUsageBytes\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\xb1\x02\n" +
	"\x17QueryShardStreamRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12\x1a\n" +
	"\binterval\x18\b \x01(\tR\binterval\x12 \n" +
	"\vaggregation\x18\t \x01(\tR\vaggregation\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\n" +
	" \x01(\rR\tchunkSize\"\xc5\x01\n" +
	"\x0fQueryShardChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\rR\achunkId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId\x125\n" +
	"\aresults\x18\x03 \x03(\v2\x1b.storage.v1.DataPointResultR\aresults\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\x88\x02\n" +
	"\x0eStorageService\x12K\n" +
	"\n" +
	"QueryShard\x12\x1d.storage.v1.QueryShardRequest\x1a\x1e.storage.v1.QueryShardResponse\x12V\n" +
	"\x10QueryShardStream\x12#.storage.v1.QueryShardStreamRequest\x1a\x1b.storage.v1.QueryShardChunk0\x01\x12Q\n" +
	"\fGetShardInfo\x12\x1f.storage.v1.GetShardInfoRequest\x1a .storage.v1.GetShardInfoResponseB7Z5github.com/soltixdb/soltix/proto/storage/v1;storagev1b\x06proto3"

var (
	file_proto_storage_v1_storage_proto_rawDescOnce sync.Once
	file_proto_storage_v1_storage_proto_rawDescData []byte
)

func file_proto_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_v1_storage_proto_rawDesc), len(file_proto_storage_v1_storage_proto_rawDesc)))
	})
	return file_proto_storage_v1_storage_proto_rawDescData
}

var file_proto_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_storage_v1_storage_proto_goTypes = []any{
	(*FieldValue)(nil),              // 0: storage.v1.FieldValue
	(*FieldsEntry)(nil),             // 1: storage.v1.FieldsEntry
	(*DeviceBlock)(nil),             // 2: storage.v1.DeviceBlock
	(*AggregatedFieldValue)(nil),    // 3: storage.v1.AggregatedFieldValue
	(*AggregatedFieldsEntry)(nil),   // 4: storage.v1.AggregatedFieldsEntry
	(*AggregatedDeviceBlock)(nil),   // 5: storage.v1.AggregatedDeviceBlock
	(*QueryShardRequest)(nil),       // 6: storage.v1.QueryShardRequest
	(*QueryShardResponse)(nil),      // 7: storage.v1.QueryShardResponse
	(*DataPointResult)(nil),         // 8: storage.v1.DataPointResult
	(*DataPoint)(nil),               // 9: storage.v1.DataPoint
	(*GetShardInfoRequest)(nil),     // 10: storage.v1.GetShardInfoRequest
	(*GetShardInfoResponse)(nil),    // 11: storage.v1.GetShardInfoResponse
	(*QueryShardStreamRequest)(nil), // 12: storage.v1.QueryShardStreamRequest
	(*QueryShardChunk)(nil),         // 13: storage.v1.QueryShardChunk
	nil,                             // 14: storage.v1.FieldsEntry.FieldsEntry
	nil,                             // 15: storage.v1.AggregatedFieldsEntry.FieldsEntry
	nil,                             // 16: storage.v1.DataPoint.FieldsEntry
}
var file_proto_storage_v1_storage_proto_depIdxs = []int32{
	14, // 0: storage.v1.FieldsEntry.fields:type_name -> storage.v1.FieldsEntry.FieldsEntry
	1,  // 1: storage.v1.DeviceBlock.fields:type_name -> storage.v1.FieldsEntry
	15, // 2: storage.v1.AggregatedFieldsEntry.fields:type_name -> storage.v1.AggregatedFieldsEntry.FieldsEntry
	4,  // 3: storage.v1.AggregatedDeviceBlock.fields:type_name -> storage.v1.AggregatedFieldsEntry
	8,  // 4: storage.v1.QueryShardResponse.results:type_name -> storage.v1.DataPointResult
	9,  // 5: storage.v1.DataPointResult.data_points:type_name -> storage.v1.DataPoint
	16, // 6: storage.v1.DataPoint.fields:type_name -> storage.v1.DataPoint.FieldsEntry
	8,  // 7: storage.v1.QueryShardChunk.results:type_name -> storage.v1.DataPointResult
	0,  // 8: storage.v1.FieldsEntry.FieldsEntry.value:type_name -> storage.v1.FieldValue
	3,  // 9: storage.v1.AggregatedFieldsEntry.FieldsEntry.value:type_name -> storage.v1.AggregatedFieldValue
	0,  // 10: storage.v1.DataPoint.FieldsEntry.value:type_name -> storage.v1.FieldValue
	6,  // 11: storage.v1.StorageService.QueryShard:input_type -> storage.v1.QueryShardRequest
	12, // 12: storage.v1.StorageService.QueryShardStream:input_type -> storage.v1.QueryShardStreamRequest
	10, // 13: storage.v1.StorageService.GetShardInfo:input_type -> storage.v1.GetShardInfoRequest
	7,  // 14: storage.v1.StorageService.QueryShard:output_type -> storage.v1.QueryShardResponse
	13, // 15: storage.v1.StorageService.QueryShardStream:output_type -> storage.v1.QueryShardChunk
	11, // 16: storage.v1.StorageService.GetShardInfo:output_type -> storage.v1.GetShardInfoResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_storage_v1_storage_proto_init() }
func file_proto_storage_v1_storage_proto_init() {
	if File_proto_storage_v1_storage_proto != nil {
		return
	}
	file_proto_storage_v1_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldValue_NumberValue)(nil),
		(*FieldValue_StringValue)(nil),
		(*FieldValue_BoolValue)(nil),
		(*FieldValue_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_v1_storage_proto_rawDesc), len(file_proto_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_v1_storage_proto = out.File
	file_proto_storage_v1_storage_proto_goTypes = nil
	file_proto_storage_v1_storage_proto_depIdxs = nil
}
