// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/wal/v1/wal.proto

package walv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType represents the type of WAL entry
type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_ENTRY_TYPE_WRITE       EntryType = 1
	EntryType_ENTRY_TYPE_DELETE      EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_WRITE",
		2: "ENTRY_TYPE_DELETE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_WRITE":       1,
		"ENTRY_TYPE_DELETE":      2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wal_v1_wal_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_wal_v1_wal_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_wal_v1_wal_proto_rawDescGZIP(), []int{0}
}

// Entry represents a single WAL entry
// This is the Protobuf replacement for JSON-encoded WAL entries
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of operation (write, delete)
	Type EntryType `protobuf:"varint,1,opt,name=type,proto3,enum=wal.v1.EntryType" json:"type,omitempty"`
	// Data identifiers
	Database   string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Collection string `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	ShardId    string `protobuf:"bytes,4,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Timestamp in RFC3339 format (for backward compatibility)
	Time string `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	// Device/entity ID
	Id string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	// Field values (key-value pairs)
	// Note: Protobuf map only supports scalar values
	// We use double for numeric values, serialize other types as needed
	Fields map[string]*FieldValue `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Entry timestamp (nanoseconds since epoch)
	Timestamp     int64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_wal_v1_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_v1_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_wal_v1_wal_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Entry) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Entry) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *Entry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetFields() map[string]*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Entry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// FieldValue represents a field value with multiple type support
// This allows storing different data types in the fields map
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_NumberValue
	//	*FieldValue_StringValue
	//	*FieldValue_BoolValue
	//	*FieldValue_IntValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_wal_v1_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_v1_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_wal_v1_wal_proto_rawDescGZIP(), []int{1}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*FieldValue_NumberValue) isFieldValue_Value() {}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

func (*FieldValue_IntValue) isFieldValue_Value() {}

var File_proto_wal_v1_wal_proto protoreflect.FileDescriptor

const file_proto_wal_v1_wal_proto_rawDesc = "" +
	"\n" +
	"\x16proto/wal/v1/wal.proto\x12\x06wal.v1\"\xc9\x02\n" +
	"\x05Entry\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.wal.v1.EntryTypeR\x04type\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\bshard_id\x18\x04 \x01(\tR\ashardId\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x121\n" +
	"\x06fields\x18\a \x03(\v2\x19.wal.v1.Entry.FieldsEntryR\x06fields\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x1aM\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.wal.v1.FieldValueR\x05value:\x028\x01\"\x9f\x01\n" +
	"\n" +
	"FieldValue\x12#\n" +
	"\fnumber_value\x18\x01 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x03H\x00R\bintValueB\a\n" +
	"\x05value*T\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTRY_TYPE_WRITE\x10\x01\x12\x15\n" +
	"\x11ENTRY_TYPE_DELETE\x10\x02B/Z-github.com/soltixdb/soltix/proto/wal/v1;walv1b\x06proto3"

var (
	file_proto_wal_v1_wal_proto_rawDescOnce sync.Once
	file_proto_wal_v1_wal_proto_rawDescData []byte
)

func file_proto_wal_v1_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_v1_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_v1_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_v1_wal_proto_rawDesc), len(file_proto_wal_v1_wal_proto_rawDesc)))
	})
	return file_proto_wal_v1_wal_proto_rawDescData
}

var file_proto_wal_v1_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wal_v1_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wal_v1_wal_proto_goTypes = []any{
	(EntryType)(0),     // 0: wal.v1.EntryType
	(*Entry)(nil),      // 1: wal.v1.Entry
	(*FieldValue)(nil), // 2: wal.v1.FieldValue
	nil,                // 3: wal.v1.Entry.FieldsEntry
}
var file_proto_wal_v1_wal_proto_depIdxs = []int32{
	0, // 0: wal.v1.Entry.type:type_name -> wal.v1.EntryType
	3, // 1: wal.v1.Entry.fields:type_name -> wal.v1.Entry.FieldsEntry
	2, // 2: wal.v1.Entry.FieldsEntry.value:type_name -> wal.v1.FieldValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_wal_v1_wal_proto_init() }
func file_proto_wal_v1_wal_proto_init() {
	if File_proto_wal_v1_wal_proto != nil {
		return
	}
	file_proto_wal_v1_wal_proto_msgTypes[1].OneofWrappers = []any{
		(*FieldValue_NumberValue)(nil),
		(*FieldValue_StringValue)(nil),
		(*FieldValue_BoolValue)(nil),
		(*FieldValue_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_v1_wal_proto_rawDesc), len(file_proto_wal_v1_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wal_v1_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_v1_wal_proto_depIdxs,
		EnumInfos:         file_proto_wal_v1_wal_proto_enumTypes,
		MessageInfos:      file_proto_wal_v1_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_v1_wal_proto = out.File
	file_proto_wal_v1_wal_proto_goTypes = nil
	file_proto_wal_v1_wal_proto_depIdxs = nil
}
